name: gugugaga
description: 咕咕嘎嘎 - 影视播放App，基于Flutter+Alist
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  url_launcher: ^6.2.0
  webview_flutter: ^4.4.0
  webview_flutter_android: ^3.13.0
  connectivity_plus: ^6.0.0
  shared_preferences: ^2.2.0
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
